name: dirtydee
favicon: null
layout_spectrum: 0.22189968614839017
typography_spectrum: 0.657123664394021
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6110788730438799
  lightness: 0.24204116314649582
  saturation: 0.8743345683906227
  rhythmicContrast: 0.6742290095426142
purpose: []
